Fix horizontal scroll
quiph/RecyclerView-FastScroller pull request #29
Opened 2020-09-12 04:19 UTC by tom5079

WIP

2020-09-12 06:10 UTC, tom5079 commented
done. resolves #3

2020-09-19 07:00 UTC, shahsurajk requested changes
Looks really good @tom5079 . Just one small nit.

2020-09-19 07:00 UTC, shahsurajk commented on recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt
> +                            moveViewByRelativeInBounds(handleImageView, currentRelativePos)
the name of this function seems a bit ambiguous, let change it to: 
```suggestion
                            moveViewByRelativeDirectionInBounds(handleImageView, currentRelativePos)
```

2020-09-19 07:11 UTC, tom5079 commented on recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt
> +                            moveViewByRelativeInBounds(handleImageView, currentRelativePos)
Alrighty 👍

2020-09-19 07:41 UTC, tom5079 commented on recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt
> +                            moveViewByRelativeInBounds(handleImageView, currentRelativePos)
@shahsurajk how about `moveViewToRelativePositionWithBounds`? What it really does is that it moves a view relative to its parent.

2020-09-19 07:50 UTC, shahsurajk commented on recyclerviewfastscroller/src/main/java/com/qtalk/recyclerviewfastscroller/RecyclerViewFastScroller.kt
> +                            moveViewByRelativeInBounds(handleImageView, currentRelativePos)
can do. works!

2020-09-19 07:59 UTC, shahsurajk approved these changes

2020-09-19 07:59 UTC, merged

2020-09-19 07:59 UTC, tom5079 commented
Great :)